# Generated by Django 4.2 on 2023-04-21 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('delivery_charge', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
