# Generated by Django 4.2 on 2023-04-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_delivery_cost_alter_order_items_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
