# Generated by Django 4.2 on 2023-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderitem_restaurant_remove_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ordering'), (1, 'Processing'), (2, 'Delivering'), (3, 'Completed')], default=0),
            preserve_default=False,
        ),
    ]
